default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: askup_development
  adapter: sqlite3

test:
  <<: *default
  database: askup_test

production:
  <<: *default
  database: askup_production
