default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: askup_development
  username: vagrant
  password: vagrant

test:
  <<: *default
  database: askup_test
  username: vagrant
  password: vagrant

production:
  <<: *default
  database: askup_production
